### ISSUE TITLE
Mind doing some pin remapping for other 32u4 boards? (Arduino Leonardo R3)

### ISSUE THREAD

**Issue by kuwoh** [bootsector/XInputPadMicro#2]
Hello I have an Arduino Leonardo R3 board and I sort of hope you could remap some buttons to some pins for that board if you don't mind that is.

![xinputleo](https://user-images.githubusercontent.com/14359681/41727827-dbd470d2-75a7-11e8-8bf4-4bd52fe4657b.png)

**Comment by kuwoh** [comment]
this or somekind of config changer? would be nice :D

**Comment by bootsector** [comment]
Hi there! Any reasons why you can't follow same pinout of the Leonardo Micro? Both boards share the same micro-controller.

**Comment by kuwoh** [comment]
some of the pins are either wired to leds sadly

**Comment by bootsector** [comment]
They should still work. Which pins have you tested and didn't work?

**Comment by kuwoh** [comment]
pb0 and pc7 is wired up to an led, etc. i don't want to mess with the smd leds on this board

**Comment by bootsector** [comment]
Yes, they are wired up to leds. But have you actually tested it? It should work out of the box without having to mess with the smd leds. Arduino micro has the same leds wired up and everything works.

**Comment by kuwoh** [comment]
i'll try it out

**Comment by kuwoh** [comment]
the pins very well work indeed but again there seems to be no input for the ss pin other than the led and i would've wished for a more modular board (making a mechanical arcade stick)

**Comment by bootsector** [comment]
Please fork this repo so one can implement the specific changes you've requested. I might send you a pull request once I have some time to play with this.

**Comment by kuwoh** [comment]
Alright. Cheers mate.
update: forked it :)

**Comment by bootsector** [comment]
Cool! Please add me as a collaborator of your forked repo. 
Repo -> Settings -> Collaborators

**Comment by kuwoh** [comment]
done :D

**Comment by kuwoh** [comment]
stupid question: how do you compile this?

**Comment by bootsector** [comment]
Install toolchain as per http://maxembedded.com/2015/06/setting-up-avr-gcc-toolchain-on-linux-and-mac-os-x/

Run make

**Comment by kuwoh** [comment]
idk what im doing wrong but it seems like it wont compile for me using make :I mind if you make a build for me? i've been stuck at this for 2 hours xD

update: got to compile it imma test it

**Comment by bootsector** [comment]
[XInputPadMicro.zip](https://github.com/bootsector/XInputPadMicro/files/2149647/XInputPadMicro.zip)
Just saw you have compiled it. Here's the .hex anyways.

**Comment by kuwoh** [comment]
thanks :D just for good measure its a good thing you compiled for me as well :) (as i was wiring up one of the wires i soldered broke off :/ have to hold off till tommorow)

**Comment by kuwoh** [comment]
everything i need works :D thanks mate
