### ISSUE TITLE
Rumble feature

### ISSUE THREAD

**Issue by EnzoMeertens** [bootsector/XInputPadMicro#3]
Hello,

Do you know if it's possible to read the "rumble" packets somehow?

I've tried everything I can think of but I am unable to make both sending and receiving of data work.
I am not shy of trying to have a stab at it myself, but the stabbing's been going on for four days straight. Any help would be highly appreciated!

**Comment by bootsector** [comment]
Hi.

Do you have some code to show of what you've tried so far? Receiving rumble request data from the host should be as simple as having something like the below inside the HID_Task function:

```
Endpoint_SelectEndpoint(0x01);

if (Endpoint_IsOUTReceived())
{
        Endpoint_Read_Stream_LE(out_buffer, sizeof(out_buffer), NULL);
        Endpoint_ClearOUT();
}
```

**Comment by EnzoMeertens** [comment]
Hello,

Thank you for your quick reply!

That's exactly what I tried first.

#define JOYSTICK_EPADDR_IN      (ENDPOINT_DIR_IN | 1)
#define JOYSTICK_EPADDR_OUT     (ENDPOINT_DIR_OUT | 1)

```
void EVENT_USB_Device_ConfigurationChanged(void) 
{
    bool ConfigSuccess = true;

    ConfigSuccess &= Endpoint_ConfigureEndpoint(JOYSTICK_EPADDR_IN, EP_TYPE_INTERRUPT, 20, 1);

    //If I enable this, the "IN" Endpoint will stop sending data but I will (sometimes) receive data.
    //ConfigSuccess &= Endpoint_ConfigureEndpoint(JOYSTICK_EPADDR_OUT, EP_TYPE_INTERRUPT, 8, 1);
}
```

```
void HID_Task(void) 
{
    /* Device must be connected and configured for the task to run */
    if (USB_DeviceState != DEVICE_STATE_Configured)
        return;

    Endpoint_SelectEndpoint(JOYSTICK_EPADDR_OUT);

    if (Endpoint_IsOUTReceived())
    {
        //This LED toggles every other time when I send data with Endpoint OUT configured.
        toggle = !toggle;
        SetLED(LED3, toggle);

        Endpoint_Read_Stream_LE(&RXData, 8, NULL);

        //This LED toggles together with LED3, so the data I am sending is actually being received.
        if(RXData[3] == 0x7B && RXData[4] == 0xDE)
                toggle2 = !toggle2;
        SetLED(LED1, toggle2);

        Endpoint_ClearOUT();
    }

    /* Select the Joystick Report Endpoint */
    Endpoint_SelectEndpoint(JOYSTICK_EPADDR_IN);

    /* Check to see if the host is ready for another packet */
    if (Endpoint_IsINReady()) 
    {   
        /* Write Joystick Report Data */
        Endpoint_Write_Stream_LE(&gamepad_state, 20, NULL);

        /* Finalize the stream transfer to send the last packet */
        Endpoint_ClearIN();
    }
}
```

The writing part works when the reading part doesn't and vice versa. I feel like I am missing something incredibly simple.

**Comment by bootsector** [comment]
You've got it pretty much right (yes, I've missed the required piece of code inside EVENT_USB_Device_ConfigurationChanged).

Do you have a protocol analyzer in order to see what's going on?

**Comment by EnzoMeertens** [comment]
I've used Wireshark (with USBPcap) to capture the two files in the zip I've attached.

These captures show the described behaviour (Endpoint IN only works if Endpoint OUT doesn't and the other way around).

Endpoint_OUT.pcapng has both Endpoint_IN enabled and Endpoint_OUT enabled.
Endpoint_IN.pcapng has Endpoint_IN enabled and Endpoint_OUT disabled.

[USB captures.zip](https://github.com/bootsector/XInputPadMicro/files/2895765/USB.captures.zip)

**Comment by bootsector** [comment]
What is your host system based on? Windows? Linux? Other? Who's generating those OUT reports with 8 bytes data? The default drivers or other application?

**Comment by EnzoMeertens** [comment]
The host system is Windows and I'm communicating with the device through the XInput.dll, so it should be using the default driver.

The OUT reports are rumble commands.

Edit; whoops. Left the email signature in.

________________________________

**Comment by bootsector** [comment]
Maybe HID_Task is crashing before having the chance to handle IN requests? Try to invert the handlers and put the IN handler before the OUT handler.

Maybe it doesn't change anything on the behavior, but I would change:

Endpoint_Read_Stream_LE(&RXData, 8, NULL);

to:

Endpoint_Read_Stream_LE(&RXData[0], 8, NULL);

or just:

Endpoint_Read_Stream_LE(RXData, 8, NULL);

Everything else looks just right.

When I have a chance, I will try to debug this from my side as well.

**Comment by EnzoMeertens** [comment]
Thank you so much for your help so far!

I will try your suggestions next thing in the morning!
________________________________

**Comment by EnzoMeertens** [comment]
Okay, so I tried changing the order so the IN handler goes before the OUT handler. That didn't change anything.

Changing the Endpoint_Read_Stream_LE to the three different options didn't seem to have any noticeable effect. 
It still just kept receiving the OUT messages but not sending any IN messages in all six cases (different order/&RXData/&RXData[0]/RXData).

**Comment by bootsector** [comment]
I'm unable to test this for the next days, but if you'd like to try it, test with the descriptors below:

Device descriptor:

```
0x12,        // bLength
0x01,        // bDescriptorType (Device)
0x00, 0x02,  // bcdUSB 2.00
0xFF,        // bDeviceClass 
0xFF,        // bDeviceSubClass 
0xFF,        // bDeviceProtocol 
0x40,        // bMaxPacketSize0 64
0x5E, 0x04,  // idVendor 0x045E
0x8E, 0x02,  // idProduct 0x028E
0x20, 0x01,  // bcdDevice 2.20
0x01,        // iManufacturer (String Index)
0x02,        // iProduct (String Index)
0x03,        // iSerialNumber (String Index)
0x01         // bNumConfigurations 1
```

Configuration descriptor:

```
0x09,        //   bLength
0x02,        //   bDescriptorType (Configuration)
0x8B, 0x00,  //   wTotalLength 139
0x04,        //   bNumInterfaces 4
0x01,        //   bConfigurationValue
0x00,        //   iConfiguration (String Index)
0xA0,        //   bmAttributes Remote Wakeup
0xFA,        //   bMaxPower 500mA

0x09,        //   bLength
0x04,        //   bDescriptorType (Interface)
0x00,        //   bInterfaceNumber 0
0x00,        //   bAlternateSetting
0x02,        //   bNumEndpoints 2
0xFF,        //   bInterfaceClass
0x5D,        //   bInterfaceSubClass
0x01,        //   bInterfaceProtocol
0x00,        //   iInterface (String Index)

0x11,        //   bLength
0x21,        //   bDescriptorType (HID)
0x10, 0x01,  //   bcdHID 1.10
0x01,        //   bCountryCode
0x25,        //   bNumDescriptors
0x81,        //   bDescriptorType[0] (Unknown 0x81)
0x14, 0x03,  //   wDescriptorLength[0] 788
0x03,        //   bDescriptorType[1] (Unknown 0x03)
0x03, 0x04,  //   wDescriptorLength[1] 1027
0x13,        //   bDescriptorType[2] (Unknown 0x13)
0x02, 0x08,  //   wDescriptorLength[2] 2050
0x03,        //   bDescriptorType[3] (Unknown 0x03)
0x03, 
0x07,        //   bLength
0x05,        //   bDescriptorType (Endpoint)
0x81,        //   bEndpointAddress (IN/D2H)
0x03,        //   bmAttributes (Interrupt)
0x20, 0x00,  //   wMaxPacketSize 32
0x04,        //   bInterval 4 (unit depends on device speed)

0x07,        //   bLength
0x05,        //   bDescriptorType (Endpoint)
0x02,        //   bEndpointAddress (OUT/H2D)
0x03,        //   bmAttributes (Interrupt)
0x20, 0x00,  //   wMaxPacketSize 32
0x08,        //   bInterval 8 (unit depends on device speed)

0x09,        //   bLength
0x04,        //   bDescriptorType (Interface)
0x01,        //   bInterfaceNumber 1
0x00,        //   bAlternateSetting
0x02,        //   bNumEndpoints 2
0xFF,        //   bInterfaceClass
0x5D,        //   bInterfaceSubClass
0x03,        //   bInterfaceProtocol
0x00,        //   iInterface (String Index)

0x1B,        //   bLength
0x21,        //   bDescriptorType (HID)
0x00, 0x01,  //   bcdHID 1.00
0x01,        //   bCountryCode
0x01,        //   bNumDescriptors
0x83,        //   bDescriptorType[0] (Unknown 0x83)
0x40, 0x01,  //   wDescriptorLength[0] 320
0x04, 0x20, 0x16, 0x85, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x16, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x07,        //   bLength
0x05,        //   bDescriptorType (Endpoint)
0x83,        //   bEndpointAddress (IN/D2H)
0x03,        //   bmAttributes (Interrupt)
0x20, 0x00,  //   wMaxPacketSize 32
0x02,        //   bInterval 2 (unit depends on device speed)

0x07,        //   bLength
0x05,        //   bDescriptorType (Endpoint)
0x04,        //   bEndpointAddress (OUT/H2D)
0x03,        //   bmAttributes (Interrupt)
0x20, 0x00,  //   wMaxPacketSize 32
0x04,        //   bInterval 4 (unit depends on device speed)

0x09,        //   bLength
0x04,        //   bDescriptorType (Interface)
0x02,        //   bInterfaceNumber 2
0x00,        //   bAlternateSetting
0x01,        //   bNumEndpoints 1
0xFF,        //   bInterfaceClass
0x5D,        //   bInterfaceSubClass
0x02,        //   bInterfaceProtocol
0x00,        //   iInterface (String Index)

0x09,        //   bLength
0x21,        //   bDescriptorType (HID)
0x00, 0x01,  //   bcdHID 1.00
0x01,        //   bCountryCode
0x22,        //   bNumDescriptors
0x86,        //   bDescriptorType[0] (Unknown 0x86)
0x07, 0x00,  //   wDescriptorLength[0] 7

0x07,        //   bLength
0x05,        //   bDescriptorType (Endpoint)
0x86,        //   bEndpointAddress (IN/D2H)
0x03,        //   bmAttributes (Interrupt)
0x20, 0x00,  //   wMaxPacketSize 32
0x10,        //   bInterval 16 (unit depends on device speed)

0x09,        //   bLength
0x04,        //   bDescriptorType (Interface)
0x03,        //   bInterfaceNumber 3
0x00,        //   bAlternateSetting
0x00,        //   bNumEndpoints 0
0xFF,        //   bInterfaceClass
0xFD,        //   bInterfaceSubClass
0x13,        //   bInterfaceProtocol
0x04,        //   iInterface (String Index)

0x06,        //   bLength
0x41,        //   bDescriptorType (Unknown)
0x00, 0x01, 0x01, 0x03
```

Notice that the OUT endpoint has changed from 0x01 to 0x02, so you need to adjust the code accordingly.

**Comment by EnzoMeertens** [comment]
That fixed it! You're the best! 

I am pretty sure I tried changing the Endpoint OUT to 0x02 before. Perhaps my LED toggle-code wasn't working then or going too fast. Either way, that fixed it, so this issue can be closed!

**Comment by bootsector** [comment]
Glad that fixed it!

Based on a quick research, it looks like we were missing a call to the Endpoint_SetEndpointDirection() function after calling Endpoint_SelectEndpoint() since we were sharing the same endpoint number (0x01) for both IN and OUT, as this article suggests:

http://fourwalledcubicle.com/blog/2008/10/sharing-endpoint-adresses/

Didn't have the chance to test the above, though.

Cheers!

**Comment by EnzoMeertens** [comment]
I will test that tomorrow and I'll let you know! :)

Is there a way I can buy you a coffee for your help?

**Comment by bootsector** [comment]
Cool! As for the coffee offering, let's make that a beer! (summer time here in Brazil) :D

**Comment by EnzoMeertens** [comment]
Sure!

How? Got a PayPal donation link? :)

**Comment by bootsector** [comment]
Nah! Just let me know when you're passing by Brazil so we can share one! ;)
Cheers!

**Comment by EnzoMeertens** [comment]
I'll keep you to it!

**Comment by eolvera85** [comment]
Hi @EnzoMeertens 

You will have the code with the modifications you made to obtain the rumble?

**Comment by EnzoMeertens** [comment]
> Hi @EnzoMeertens
> 
> You will have the code with the modifications you made to obtain the rumble?

Heya! 

What do you mean exactly?
